### ISSUE TITLE
A lot of raw pointers are being passed around, these should be std::shared_ptr

### ISSUE THREAD

**Issue by bobdesaunois** [bobdesaunois/cpp-game-of-life#2]
A lot of raw pointers are being passed around the Map class.
They should definitely become std::shared_ptr instances to make sure that ownership doens't become a problem later on and we're not left with exiled pointers.

**Comment by bobdesaunois** [comment]
Unsure whether this is actually a thing.
Read some articles about std::shared_ptr being shit when pointing to existing objects

Also this:

"It is important that shared_ptr should not point to any object which is already managed by another object."

**Comment by AbrilRBS** [comment]
I've found this issue while looking for something to do, and after taking a look at the code, I have to ask you: Why does GetCells() return a pointer to a vector? What was your idea behind it?

(_Btw any sane compiler would optimize it even with -O0, but https://github.com/bobdesaunois/cpp-game-of-life/blob/master/cpp-game-of-life/Map.cpp#L105 is rather peculiar. Why not just simply return the boolean result instead of branching. The less branching, the better it is!_)

Regards
